---
title: "Map Using Leaflet"
author: "Abhijeet"
date: "2023-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 1. Synopsis
This Report is a assignment of the Developing Data Products Course of [Data Science Specialization](https://www.coursera.org/specializations/jhu-data-science) by Johns Hopkins University on Coursera.

## 1.1 Creating Map
1. The Location is the location of the college I studied.
2. Icon is taken from wikipedia web page.
```{r}

suppressWarnings(library(leaflet))

# Logo Icon
IITGIcon <- makeIcon(iconUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Indian_Institute_of_Technology_Goa_Logo.svg/220px-Indian_Institute_of_Technology_Goa_Logo.svg.png", 
                     iconWidth = 45, iconHeight = 40, 
                     iconAnchorX = 45, iconAnchorY = 40)

# Location- Longitude and latitude        
IITGLocation<-data.frame(
  lng= 73.9798,lat= 15.4226
)

# Map generation
leaflet(IITGLocation) %>% addTiles() %>% addMarkers(icon=IITGIcon, popup = "College where I studied(Goa, India)")
```

